# Generated by Django 4.0.5 on 2022-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                check=models.Q(("sexo__in", ["M", "F", "I"])),
                name="core_animal_sexo_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                check=models.Q(("grupo_idade__in", ["F", "A", "I"])),
                name="core_animal_grupo_idade_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                check=models.Q(("porte__in", ["G", "M", "P"])),
                name="core_animal_porte_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ["I", "A", "C"])),
                name="core_post_status_valid",
            ),
        ),
    ]
